---
:points:
- :title: Birmingham
  :country: Großbritannien und Nordirland
  :lon: -1.8904009999999971
  :lat: 52.48624299999999
  :type: :visit
- :title: London
  :country: Großbritannien und Nordirland
  :date: '2011-11-06'
  :lon: -0.12775829999998223
  :lat: 51.5073509
  :type: :visit
- :title: Cambridge
  :country: Großbritannien und Nordirland
  :lon: 0.12181699999996454
  :lat: 52.205337
  :type: :visit
  :date: '2011-03-18'
- :title: Oxford
  :country: Großbritannien und Nordirland
  :date: '2010-10-23'
  :lon: -1.2577263000000585
  :lat: 51.7520209
  :type: :visit
- :title: Edinburgh
  :country: Großbritannien und Nordirland
  :lon: -3.188266999999996
  :lat: 55.953252
  :type: :visit
- :title: Aberdeen
  :country: Großbritannien und Nordirland
  :lon: -2.094278000000031
  :lat: 57.149717
  :type: :visit
- :title: Brighton
  :country: Großbritannien und Nordirland
  :date: '2012-12-11'
  :lon: -0.13716299999998682
  :lat: 50.82253000000001
  :type: :visit
- :title: Dundee
  :country: Großbritannien und Nordirland
  :lon: -2.970721000000026
  :lat: 56.462018
  :type: :visit
- :title: Glasgow
  :country: Großbritannien und Nordirland
  :lon: -4.251805999999988
  :lat: 55.864237
  :type: :visit
- :title: Dublin
  :country: Irland
  :lon: -6.260309699999993
  :lat: 53.3498053
  :type: :visit
- :title: Chania
  :country: Griechenland
  :date: '2009-06-24'
  :lon: 24.01803670000004
  :lat: 35.5138298
  :type: :visit
- :title: Berlin
  :country: Deutschland
  :lon: 13.404953999999975
  :lat: 52.52000659999999
  :type: :visit
- :title: Leipzig
  :comment: Games Convention 2006
  :country: Deutschland
  :lon: 12.373074699999961
  :lat: 51.3396955
  :type: :gallery
  :gallery: flickr,user=cyberkov,set=72157594269149430
- :title: Paris
  :country: Frankreich
  :date: '2011-04-13'
  :lon: 2.3522219000000177
  :lat: 48.856614
  :type: :visit
- :title: Venedig
  :country: Italien
  :lon: 12.31551509999997
  :lat: 45.4408474
  :type: :visit
- :title: Madeira
  :country: Portugal
  :date: '2011-08-03'
  :lon: -16.959472300000016
  :lat: 32.76070740000001
  :type: :visit
- :title: Lissabon
  :country: Portugal
  :lon: -9.139336599999979
  :lat: 38.7222524
  :type: :visit
- :title: Porto
  :country: Portugal
  :lon: -8.629105299999992
  :lat: 41.1579438
  :type: :visit
- :title: Cabo da Roca
  :country: Portugal
  :lon: -9.498888899999997
  :lat: 38.7802778
  :type: :visit
- :title: Santorini
  :country: Griechenland
  :lon: 25.461509200000023
  :lat: 36.3931562
  :type: :visit
- :title: Nikosia
  :country: Cyprus
  :lon: 33.36666700000001
  :lat: 35.166667
  :type: :visit
- :title: Ljubljana
  :country: Slowenien
  :lon: 14.505751499999974
  :lat: 46.0569465
  :type: :visit
- :title: "Straßburg"
  :country: Frankreich
  :lon: 7.752111300000024
  :lat: 48.5734053
  :type: :visit
- :title: Athen
  :country: Griechenland
  :lon: 23.729359899999963
  :lat: 37.983917
  :type: :visit
- :title: Bratislava
  :country: Slowakei
  :date: '2012-11-14'
  :lon: 17.107137299999977
  :lat: 48.1458923
  :type: :visit
- :title: Orléans
  :comment: '1990'
  :country: Frankreich
  :date: '1990-06-03'
  :lon: 1.9092510000000402
  :lat: 47.902964
  :type: :visit
- :title: Blois
  :comment: '1990'
  :country: Frankreich
  :date: '1990-06-03'
  :lon: 1.3359474999999748
  :lat: 47.58609209999999
  :type: :visit
- :title: Amboise
  :comment: '1990'
  :country: Frankreich
  :date: '1990-06-03'
  :lon: 0.9844070000000329
  :lat: 47.413326
  :type: :visit
- :title: Tours
  :comment: '1990'
  :country: Frankreich
  :date: '1990-06-03'
  :lon: 0.6848400000000083
  :lat: 47.394144
  :type: :visit
