:map:
  :data: :visited
  :width: "80%"
  :height: "90%"
  :zoom_control: true
  :map_type_control: true
  :street_view_control: true
  :overview_control: false
  :pan_control: true
  :title: My Travels
  :cluster: true
  :cluster_grid_size: 30
  :cluster_minumum_size: 3
  :cluster_zoom_on_click: false
  :show_geocode_link: true
  :map_types: [hybrid, roadmap, satellite, terrain, osm, watercolor, toner, darkmatter, positron, mapquest]
  :default_map_type: roadmap


:views:
  :default:
    :lat: 20
    :lon: 0
    :zoom: 3
    :description: World
  :europe:
    :lat: 48.195387
    :lon: 10.634766
    :zoom: 6
    :description: Europe

:types:
  :visit:
    :icon: /mapicons/tourism/visited.png
    :description: Visit
  :transit:
    :icon: /mapicons/transportation/airport.png
    :description: Transit
  :lived:
    :icon: /mapicons/friends-family/home-2.png
    :description: Lived
  :wishlist:
    :icon: /mapicons/tourism/notvisited.png
    :description: Wishlist
  :gallery:
    :icon: /mapicons/stores/photography.png
    :description: Gallery
    :legend: false

:sets:
  :visited:
    :description: Visited
    :data: travels
  :wishlist:
    :description: Travel Wishlist
    :data: wishlist
