:map:
  :data:
    - europe.yaml
    - america.yaml
  :width: "80%"
  :height: "90%"
  :zoom_control: true
  :map_type_control: true
  :street_view_control: true
  :overview_control: false
  :pan_control: true
  :title: My Travels
  :cluster: true
  :cluster_grid_size: 30
  :cluster_minumum_size: 3
  :cluster_zoom_on_click: false
  :cluster_image_path: /cluster/cluster-RED-
  :cluster_image_extension: png
  :cluster_image_sizes: [24, 26, 31, 37, 43]
  :show_geocode_link: true
  :map_types: [hybrid, roadmap, satellite, terrain, osm, watercolor, toner, darkmatter, positron, mapquest]
  :default_map_type: roadmap


:views:
  :default:
    :lat: 20
    :lon: 0
    :zoom: 3
    :description: World
  :europe:
    :lat: 48.195387
    :lon: 10.634766
    :zoom: 6
    :description: Europe

:types:
  :visit:
    :icon: /markers/marker-RED-REGULAR.png
    :description: Visit
  :transit:
    :icon: /markers/marker-BLUE-REGULAR.png
    :description: Transit
  :lived:
    :icon: /markers/marker-GREEN-REGULAR.png
    :description: Lived
